language: java
jdk:
 - oraclejdk8

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install

addons:
   sonarcloud:
       organization: "sweihmws2018-19"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Pdev sonar:sonar
  - mvn org.apache.maven.plugins:maven-assembly-plugin:2.6:assembly -DdescriptorId=jar-with-dependencies package

deploy:
  provider: Alkolexa INC
  function_name: "Alkolexa"
  region: "eu-middle-1"
  role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
  runtime: "jdk1.8"
  handler_name: "AlkolexaStreamHandler"